version: "3"
services:
  migrant:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/opt/app
    depends_on:
      - matchvote_db

  matchvote_db:
    image: postgres:9.6
    ports:
      - "5653:5432"
